// =============================================================================
// alert.rs -- Threshold-Based Alert System
// =============================================================================
//
// In ISRO's Mission Control, anomaly detection is critical. If engine
// temperature exceeds a threshold, if fuel pressure drops below a minimum,
// or if the spacecraft deviates from its planned trajectory -- alerts fire
// immediately so the team can respond.
//
// VaayuSanket does the same for your system: it checks each metric against
// configurable thresholds and generates alerts when something needs attention.
// =============================================================================

use crate::config::Config;
use crate::monitor::SystemSnapshot;

/// Alert severity levels, inspired by spacecraft anomaly classification.
///
/// - Warning: approaching dangerous levels, pay attention
/// - Critical: threshold exceeded, action needed
#[derive(Debug, Clone, PartialEq)]
pub enum AlertLevel {
    /// Approaching threshold -- like a "caution" indicator on the dashboard
    Warning,
    /// Threshold exceeded -- like a "warning" klaxon in Mission Control
    Critical,
}

/// A single alert generated by the monitoring system.
///
/// Contains the severity level, which metric triggered it, and a
/// human-readable message explaining the situation.
#[derive(Debug, Clone)]
pub struct Alert {
    /// How severe is this alert?
    pub level: AlertLevel,

    /// Which metric triggered the alert (e.g., "CPU", "Memory", "Disk: /")
    pub metric: String,

    /// Human-readable description of the alert
    pub message: String,
}

/// Check all system metrics against configured thresholds.
///
/// This is the "anomaly detection" pass that runs every monitoring tick.
/// It inspects CPU usage, memory usage, and disk usage, comparing each
/// against the thresholds defined in the Config.
///
/// # Arguments
/// * `snapshot` - Current system metrics
/// * `config` - Configuration with threshold values
///
/// # Returns
/// A Vec of Alert structs (empty if everything is nominal)
pub fn check_alerts(snapshot: &SystemSnapshot, config: &Config) -> Vec<Alert> {
    let mut alerts = Vec::new();

    // ---- CPU Alert ----
    // Check if overall CPU usage exceeds the threshold.
    // A warning fires at threshold - 10%, critical at the threshold itself.
    let cpu_usage = snapshot.cpu.usage_percent;
    if cpu_usage >= config.alert_cpu_threshold {
        alerts.push(Alert {
            level: AlertLevel::Critical,
            metric: "CPU".to_string(),
            message: format!(
                "CPU usage at {:.1}% (threshold: {:.0}%)",
                cpu_usage, config.alert_cpu_threshold
            ),
        });
    } else if cpu_usage >= config.alert_cpu_threshold - 10.0 {
        alerts.push(Alert {
            level: AlertLevel::Warning,
            metric: "CPU".to_string(),
            message: format!(
                "CPU usage approaching threshold at {:.1}% (threshold: {:.0}%)",
                cpu_usage, config.alert_cpu_threshold
            ),
        });
    }

    // ---- Memory Alert ----
    let mem_usage = snapshot.memory.usage_percent;
    if mem_usage >= config.alert_memory_threshold {
        alerts.push(Alert {
            level: AlertLevel::Critical,
            metric: "Memory".to_string(),
            message: format!(
                "Memory usage at {:.1}% (threshold: {:.0}%)",
                mem_usage, config.alert_memory_threshold
            ),
        });
    } else if mem_usage >= config.alert_memory_threshold - 10.0 {
        alerts.push(Alert {
            level: AlertLevel::Warning,
            metric: "Memory".to_string(),
            message: format!(
                "Memory usage approaching threshold at {:.1}% (threshold: {:.0}%)",
                mem_usage, config.alert_memory_threshold
            ),
        });
    }

    // ---- Disk Alerts ----
    // Check each disk independently. A disk at 90%+ is always critical,
    // regardless of config thresholds (running out of disk space is always bad).
    for disk in &snapshot.disks {
        if disk.usage_percent >= 95.0 {
            alerts.push(Alert {
                level: AlertLevel::Critical,
                metric: format!("Disk: {}", disk.mount_point),
                message: format!(
                    "Disk '{}' at {:.1}% capacity -- nearly full!",
                    disk.mount_point, disk.usage_percent
                ),
            });
        } else if disk.usage_percent >= 85.0 {
            alerts.push(Alert {
                level: AlertLevel::Warning,
                metric: format!("Disk: {}", disk.mount_point),
                message: format!(
                    "Disk '{}' at {:.1}% capacity",
                    disk.mount_point, disk.usage_percent
                ),
            });
        }
    }

    // ---- Swap Alert ----
    // High swap usage indicates the system is running low on physical RAM
    // and is using disk as overflow -- a major performance concern.
    if snapshot.memory.swap_total_bytes > 0 {
        let swap_usage = snapshot.memory.swap_usage_percent;
        if swap_usage >= 80.0 {
            alerts.push(Alert {
                level: AlertLevel::Critical,
                metric: "Swap".to_string(),
                message: format!(
                    "Swap usage at {:.1}% -- system is heavily swapping!",
                    swap_usage
                ),
            });
        } else if swap_usage >= 50.0 {
            alerts.push(Alert {
                level: AlertLevel::Warning,
                metric: "Swap".to_string(),
                message: format!("Swap usage at {:.1}%", swap_usage),
            });
        }
    }

    alerts
}

/// Format and display alerts to the terminal with appropriate colors.
///
/// # Arguments
/// * `alerts` - The alerts to display
/// * `no_color` - If true, omit ANSI color codes
pub fn display_alerts(alerts: &[Alert], no_color: bool) {
    if alerts.is_empty() {
        return; // All systems nominal -- nothing to report!
    }

    let (red, yellow, reset, bold) = if no_color {
        ("", "", "", "")
    } else {
        ("\x1b[31m", "\x1b[33m", "\x1b[0m", "\x1b[1m")
    };

    println!("{}{}>> ALERTS{}", bold, red, reset);
    println!("   {}", "-".repeat(56));

    for alert in alerts {
        let (icon, color) = match alert.level {
            AlertLevel::Critical => ("[CRITICAL]", red),
            AlertLevel::Warning => ("[WARNING] ", yellow),
        };

        println!(
            "   {}{} [{}] {}{}",
            color, icon, alert.metric, alert.message, reset
        );
    }
    println!();
}
